version: 2
updates:
- package-ecosystem: nuget
  labels:
    - "dependencies"
  commit-message:
    prefix: "(deps)"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  labels:
    - "dependencies"
  commit-message:
    prefix: "(build deps)"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  labels:
    - "dependencies"
  commit-message:
    prefix: "(docs deps)"
  directory: "/"
  schedule:
    interval: daily
