on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      arch:
        required: true
        type: string
      docker_distros:
        required: true
        type: string
      push_images:
        required: true
        type: boolean
      dockerhub_oidc_connection_id:
        required: true
        type: string
env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"
  PUSH_IMAGES: ${{ inputs.push_images }}

permissions:
  id-token: write
  packages: write

jobs:
  build_deps:
    name: ${{ matrix.docker_distro }}
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
      matrix:
        docker_distro: ${{ fromJson(inputs.docker_distros) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Use cached cake frosting
        id: cache-cake
        uses: actions/cache@v6
        with:
          path: run
          key: run-${{ runner.os }}-${{ hashFiles('./build/**') }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: build/global.json

      - name: Set up Docker
        uses: ./.github/actions/docker-setup

      - name: Publish image to DockerHub
        if: env.PUSH_IMAGES == 'true'
        uses: ./.github/actions/build-deps
        with:
          arch: ${{ inputs.arch }}
          docker_distro: ${{ matrix.docker_distro }}
          docker_registry: docker.io
          docker_registry_name: dockerhub
          dockerhub_organization: gittools
          dockerhub_oidc_connection_id: ${{ inputs.dockerhub_oidc_connection_id }}

      - name: Publish image to GitHub
        uses: ./.github/actions/build-deps
        with:
          arch: ${{ inputs.arch }}
          docker_distro: ${{ matrix.docker_distro }}
          docker_registry: ghcr.io
          docker_registry_name: github
          docker_registry_username: ${{ github.repository_owner }}
          docker_registry_password: ${{ github.token }}
